name: cilium-crossplane-resources
serviceType: managed

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

image:
  registry: quay.io
  name: giantswarm/cilium-crossplane-resources
  tag: v0.0.1
  pullPolicy: IfNotPresent
